### PR TITLE
Multiple value fix

### PR DESCRIPTION
**Pull request by dayer4b**
This pull request contains a fix for the problem raised in Issue #5

### CODE REVIEW

**Comment by pencil** [comment]
CASino 4.0 supports multiple-values for a single field. Basically we can change [this line](https://github.com/rbCAS/casino-ldap_authenticator/blob/eb6f778e04587cd9ee79a5580b621f8c78d28c33/lib/casino/ldap_authenticator.rb#L85) to:

``` ruby
result[index_result] = value
```

I currently don't have the infrastructure to test it but if you are still interested, you might want to give it a try.

**Comment by twyfordr** [comment]
We ran into this bug today.  Will this patch (or a similiar one) be included in any upcoming release?

**Comment by pencil** [comment]
I didn't have the chance to test this change. I'm pretty sure most CAS client implementations can't handle multiple values for the same key but that would have to be tested as well.

**Comment by pencil** [comment]
Closing this and continuing in #5

**Pull request closed without merging**
